/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module control_finca (
  input I0_2,
  input I0_3,
  input I0_4,
  input I0_1,
  output Q0_1,
  output Q0_2,
  output Q0_4,
  output Q0_3,
  output Q0_5,
  output Q0_6,
  output Q0_7
);
  wire nP;
  wire Q0_4_temp;
  assign nP = ~ I0_4;
  assign Q0_3 = ~ I0_2;
  assign Q0_1 = ((I0_3 | ~ I0_1) & nP & I0_2);
  assign Q0_4_temp = ((I0_1 | I0_2) & nP);
  assign Q0_2 = Q0_4_temp;
  assign Q0_4 = Q0_4_temp;
  assign Q0_5 = I0_1;
  assign Q0_6 = I0_3;
  assign Q0_7 = I0_4;
endmodule
